### ISSUE TITLE
Liara deploy problem

### ISSUE THREAD

**Issue by mojtabakaviani** [liara-cloud/cli#140]
ModuleLoadError: [MODULE_NOT_FOUND] import() failed to load 
 ›   /opt/hostedtoolcache/node/18.18.0/x64/lib/node_modules/@liara/cli/lib/comm
 ›   ands/deploy.js: Cannot find module 'call-bind'
 ›   Require stack:
 ›   - /opt/hostedtoolcache/node/18.18.0/x64/lib/node_modules/@liara/cli/node_m
 ›   odules/@ljharb/through/index.js
 ›   Code: MODULE_NOT_FOUND

**Comment by vashian** [comment]
@mojtabakaviani  To help us assist you better, we need some additional information about your environment and setup. Please provide the following details:

**Environment Details:**
- Node.js Version: [Please specify your Node.js version]
- Liara CLI Version: [Please specify your Liara CLI version]
- Operating System: [Specify your OS, e.g., Linux, macOS, Windows]

**Steps to Reproduce:**
If possible, provide the steps or commands that led to the error. This will help us understand the context in which the issue occurred.

**Additional Information:**
- Please share any relevant configuration files or scripts that you are using.
- If you can reproduce the issue consistently, provide the specific command or code that causes the error.

**Screenshots:**
If applicable, provide screenshots or any visual aids that might help illustrate the problem.

**Comment by mojtabakaviani** [comment]
@vashian thanks to replay.

i use github workflows with node.js 18, install @liara/cli, this error raised sometimes and not allow to complete actions.

**Comment by vashian** [comment]
@mojtabakaviani  Issue is coming from [@ljharb/through](https://github.com/ljharb/through)

Thanks for the report. The issue has been fixed upstream. Additionally, we have bumped our dependencies' version, and a release with these updates will be available soon.
