### ISSUE TITLE
Many times github action failed, because upload failed 

### ISSUE THREAD

**Issue by mojtabakaviani** [liara-cloud/cli#150]
✖ Upload failed.

@liara/cli/5.1.1 linux-x64 node-v[18](https://github.com/mojtabakaviani/financial/actions/runs/6840108487/job/18599017428#step:11:19).18.2

 ›   Error: Deployment failed.
 ›   To get help, visit our documentation at: https://docs.liara.ir/
 ›
 ›   Additionally, you can also retry the build with the debug flag:
 ›       $ liara deploy --debug
Error: Process completed with exit code 2.

**Comment by mojtabakaviani** [comment]
✖ Upload failed.

 ›   Error: Unexpected end of JSON input
Error: Process completed with exit code 2.

**Comment by vashian** [comment]
Hi :wave: @mojtabakaviani
 
Thank you for submitting this issue. To better understand and troubleshoot the problem, we kindly ask you to follow the steps below:

##### 1. Retry Deployment with Debug Flag:
Please run the deployment command with the `--debug` flag to provide additional information. Execute the following command:

```bash
liara deploy --debug
```
This will generate more detailed logs that can assist us in diagnosing the issue.
After running the command with the `--debug` flag, share the complete logs and error stack trace.

##### 2. Include liara.yml or GitHub Action File:
Additionally, if applicable, include your `liara.yml` file or the GitHub Action file used for the deployment. This will help us review your configuration and identify any potential issues.

**Comment by mojtabakaviani** [comment]
Currently, this problem has not occurred, if i see it, provide the details.

**Comment by mojtabakaviani** [comment]
Hi @mhemrg
 I think this error raised when can't upload files to liara iran location servers from github, beacuse not access!

- Creating an archive...
   ignoring liara.json
Compressed size: 57.66MB (use .gitignore to reduce the size)
✖ Upload failed.

[debug] [2023-12-03T09:40:34.667Z] 
 ›   Error: Unexpected end of JSON input
Error: Process completed with exit code 2.

**Comment by mojtabakaviani** [comment]
Hi @vashian, few days upload failed many times with error Timeout awaiting 'request' for 10000ms.

**Comment by mojtabakaviani** [comment]
Hi @mhemrg, github action can't access your server and show this error.
```
Error: Oops! It seems like there's a disruption, and the request has timed
out (Error 408). Please check your internet connection and try again.
```
