### ISSUE TITLE
[bug] - liara deployment freezes

### ISSUE THREAD

**Issue by hosseinmirzapur** [liara-cloud/cli#165]
So many times, when I try to run `liara deploy` and provide all the credentials in liara.json file, the compression and uploading process takes forever like it freezes.

**Comment by jarqvi** [comment]
Hi there👋

please use `--debug` flag in `liara deploy` command, and take a screenshot and attach it.

**Comment by hosseinmirzapur** [comment]
So when i run `liara deploy --debug` this is where it freezes:

![image](https://github.com/liara-cloud/cli/assets/63141950/22776b12-19a6-46bf-b274-e33c505ba19a)

It seems like when the liara network is busy, it happens but i've checked the code for liara/cli and what I've seen is, the request timeout is set to `undefined` surprisingly.

**Comment by hosseinmirzapur** [comment]
liara --version gave me this:

```
@liara/cli/5.6.0 linux-x64 node-v16.4.0
```

**Comment by jarqvi** [comment]
Since this is the first time I encounter this error, I request you to update your liara-cli version to `5.7.0-beta.4` and check again

**Comment by hosseinmirzapur** [comment]
thanks for answering. yes it's fine
