### ISSUE TITLE
bug: `liara logs --since=X` should fetch all logs from `since` to now.

### ISSUE THREAD

**Issue by erfanium** [liara-cloud/cli#170]
# Actual Behavior
when using liara logs command like this:
```
liara logs --since=1714024894
```
cli will print just a few logs, but it should be many.

# Expected behavior
print all the logs from `1714024894` to now

# Additional Context
That's because when I don't use `--follow`, liara cli only makes one single API call to the sever. but in case of `--since`, cli should do many API calls to the server in a loop

**Comment by eyeamnoob** [comment]
Hello,
We're thrilled to see people getting involved with Liara's open source projects!
We have a limitation when it comes to fetching logs. Retrieving all logs since `X` can result in a large query. To avoid this, we have added pagination. If you would like to see the most recent logs, use a larger `X` (meaning closer to now) or simply add `--follow`.

**Comment by erfanium** [comment]
> We have a limitation when it comes to fetching logs. Retrieving all logs since X can result in a large query

I completely understand why this is a heavy task to perform. However, the current implementation of liara logs cannot address many production-grade needs.

Let's say there's a bug in production in my app. I need to somehow get the logs from the last 15 minutes to start the investigation.
If I use plain Docker, this need can be easily satisfied with `docker logs NAME --since 15m`, but I cannot do the same with Liara CLI.


>  use a larger X (meaning closer to now)

Not an option. because I only get a few logs which is not enough to start an investigation

> or simply add --follow

This hack works, but there's two problems:

1. It's slow because it will fetch the next page after one second. it may take *minutes* to save fairly large amount of logs.
2. The purpose of `--follow` is clearly different. I don't really want to follow logs.


Overall, I would be very happy if this business-need gets implemented.
Thanks!

**Comment by mhemrg** [comment]
Isn't it possible to continue fetching logs until the present moment or until there are no more logs available?

**Comment by eyeamnoob** [comment]
On the logs endpoint, we've got a `direction` parameter. Perhaps we could consider passing it through the CLI.
@mhemrg

**Comment by mhemrg** [comment]
How does it help?

**Comment by mhemrg** [comment]
@parishahla PTAL.

**Comment by parishahla** [comment]
This issue got fixed!
